version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
    links:
      - "database:db"
    env_file:
      - .env

  nginx:
    container_name: slim_nginx
    build:
      context: ./docker/nginx
    ports:
      - ${APP_EXPOSED_PORT}:80
    volumes:
      - .:/var/www/slim_app/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  database:
    build:
      context: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: 'database'
    restart: 'always'
    ports:
      - ${MYSQL_EXPOSED_PORT}:3306
    env_file:
      - .env
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: 'slim-phpmyadmin'
    links:
      - "database:db"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - ${PHPMYADMIN_EXPOSED_PORT}:80
    volumes:
      - /sessions
